[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
iat_checkout = "GN2d9tgQvwWqFaGuVomqBxcngW8c3CPWe4JRG6bP4rD"

[provider]
cluster = "Devnet"
wallet = "~/pool-wallet.json"

[workspace]
members = ["programs/iat-checkout"]
