from typing import Any, Dict
import json
import requests

from iat.api.db import (
    get_agent_db,
    get_agents_for_service_db,
    update_order_db,
    run_foundation_controlled_seller_execution_db,
    verify_seller_execution_result_db,
    run_foundation_decision_db,
)


from iat.api.multi_exec import (
    compute_required_agent_count,
    select_top_agents,
    multi_call,
    select_best_result,
    build_final_buyer_delivery,
    compute_consensus_strength,
    build_foundation_buyer_report,
)



def _ensure_dict(value, default=None):
    default = default or {}

    if isinstance(value, dict):
        return value

    if isinstance(value, str):
        try:
            parsed = json.loads(value)
            return parsed if isinstance(parsed, dict) else default
        except Exception:
            return default

    return default


def generate_service_result(service_name, query=None):
    return {
        "status": "success",
        "service": service_name,
        "query": query,
        "summary": "Foundation fallback result generated by protocol runtime.",
        "recommendations": [],
        "confidence": 0.5,
    }


def build_foundation_context(order):
    buyer_intent = _ensure_dict(order.get("buyer_intent") or {})

    return {
        "generated_by": "iat_protocol_runtime",
        "service": order.get("service"),
        "goal": buyer_intent.get("goal"),
        "requirements": order.get("requirements", {}),
        "trusted": True,
        "buyer_data_stripped": True,
        "foundation_mediated": True,
    }


def deliver_service(order, tx_signature):
    order = order or {}

    execution_mode = str(
        order.get("execution_mode") or "foundation_direct"
    ).lower()

    # Foundation-mediated supplier pipeline.
    # Buyer-facing delivery remains foundation-only.
    # Seller agents are internal suppliers and never receive raw buyer access.
    if execution_mode == "foundation_supplier_pipeline":
        return run_foundation_supplier_pipeline(order)

    # Foundation consensus execution pipeline.
    if execution_mode == "foundation_consensus":
        from iat.api.multi_exec import (
            compute_required_agent_count,
            select_top_agents,
            multi_call,
            select_best_result,
            build_final_buyer_delivery,
            compute_consensus_strength,
        )

        from iat.api.db import get_available_seller_execution_agents_db
        from iat.api.execution_engine import rank_agents
        from iat.seller_runtime.multi_runtime import run_multi_seller_runtime

        service = order.get("service")

        foundation_context = order.get("foundation_context") or {}
        economic_snapshot = (
            foundation_context.get("economic_snapshot", {})
            if isinstance(foundation_context, dict)
            else {}
        )

        base_required_count = compute_required_agent_count(order)

        economic_recommended_consensus = int(
            economic_snapshot.get("recommended_consensus")
            or 0
        )

        required_count = max(
            base_required_count,
            economic_recommended_consensus,
            1,
        )

        eligible = get_available_seller_execution_agents_db(
            service=service,
            specialization=None,
            limit=max(required_count, 3),
        )

        seller_candidates = eligible.get("agents", []) if eligible.get("status") == "ok" else []

        ranked_sellers = rank_agents([
            {
                **candidate,
                "agent_id": candidate.get("agent_id"),
                "agent_type": "seller_agent",
                "price_iat": candidate.get("price") or candidate.get("price_iat"),
                "trust_score": candidate.get("trust_score", 50),
                "risk_score": candidate.get("risk_score", 50),
                "runtime_health_score": candidate.get("runtime_health_score", 50),
                "governance_score": candidate.get("governance_score", 50),
                "reputation": candidate.get("reputation", 0.5),
                "success_rate": candidate.get("success_rate", 0.5),
                "latency": candidate.get("latency", 1),
            }
            for candidate in seller_candidates
        ])[:required_count]

        if ranked_sellers:
            runtime_context = {
                "task": order.get("query"),
                "scope": {
                    "asset": "BTC" if "btc" in str(order.get("query", "")).lower() else None,
                    "horizon": "short_term" if "short" in str(order.get("query", "")).lower() else None,
                    "service": service,
                },
                "required_format": "structured_supplier_contribution",
                "service": service,
                "trusted_input_only": True,
                "foundation_mediated": True,
                "buyer_data_stripped": True,
            }

            multi_runtime = run_multi_seller_runtime(
                service=service,
                execution_context=runtime_context,
                candidate_agents=ranked_sellers,
                max_workers=required_count,
            )

            selected_agents = ranked_sellers
            results = multi_runtime.get("results", [])
            consensus_strength = compute_consensus_strength(results)
            best_result = select_best_result(results)

            if not best_result:
                return {
                    "error": "seller_runtime_consensus_failed",
                    "message": "No valid seller runtime consensus result produced.",
                    "execution_mode": execution_mode,
                    "agents_called": [
                        a.get("agent_id")
                        for a in selected_agents
                    ],
                    "multi_runtime": multi_runtime,
                }

            final_delivery = build_final_buyer_delivery(
                best_result,
                results,
            )

            foundation_decision = (
                order.get("foundation_decision")
                or run_foundation_decision_db(order.get("order_id"))
            )

            try:
                foundation_report = build_foundation_buyer_report(
                    foundation_decision,
                    fallback_delivery=final_delivery,
                )
            except Exception as exc:
                foundation_report = {
                    **final_delivery,
                    "delivery_mode": "foundation_seller_runtime_consensus_report_fallback",
                    "foundation_report_error": str(exc),
                }

            return {
                "status": "seller_runtime_consensus_delivered",
                "execution_mode": execution_mode,
                "agents_called": [
                    a.get("agent_id")
                    for a in selected_agents
                ],
                "seller_agents_called": [
                    a.get("seller_agent_id")
                    for a in selected_agents
                ],
                "consensus_agents_count": len(selected_agents),
                "required_consensus_agents_count": required_count,
                "base_required_consensus_agents_count": base_required_count,
                "economic_recommended_consensus": economic_recommended_consensus,
                "economic_snapshot_used": bool(economic_snapshot),
                "consensus_strength": consensus_strength,
                "foundation_decision": foundation_decision,
                "multi_runtime": multi_runtime,
                "best_result": best_result,
                "result": foundation_report,
                "policy": {
                    "buyer_never_contacts_seller": True,
                    "seller_never_contacts_buyer": True,
                    "seller_agents_are_suppliers_only": True,
                    "foundation_agents_keep_final_authority": True,
                    "protocol_core_sovereignty_reserved": True,
                },
            }

        all_agents = get_agents_for_service_db(order.get("service"))

        foundation_agents = [
            a for a in all_agents
            if str(a.get("agent_type", "")).lower() == "foundation"
            and bool(a.get("available", True))
        ]

        foundation_decision = order.get("foundation_decision") or {}

        preferred_agent_id = (
            foundation_decision.get("decision", {})
            .get("selected_agent_id")
        )

        if preferred_agent_id:
            preferred = [
                a for a in foundation_agents
                if a.get("agent_id") == preferred_agent_id
            ]

            remaining = [
                a for a in foundation_agents
                if a.get("agent_id") != preferred_agent_id
            ]

            selected_agents = (preferred + remaining)[:required_count]
        else:
            selected_agents = select_top_agents(
                foundation_agents,
                limit=required_count,
                order=order,
            )

        results = multi_call(selected_agents, order)

        consensus_strength = compute_consensus_strength(results)

        best_result = select_best_result(results)

        if not best_result:
            return {
                "error": "consensus_failed",
                "message": "No valid consensus result produced.",
                "execution_mode": execution_mode,
                "agents_called": [
                    a.get("agent_id")
                    for a in selected_agents
                ],
            }

        final_delivery = build_final_buyer_delivery(
            best_result,
            results,
        )

        foundation_decision = (
        order.get("foundation_decision")
        or run_foundation_decision_db(order.get("order_id"))
    )

        try:
            foundation_report = build_foundation_buyer_report(
                foundation_decision,
                fallback_delivery=final_delivery,
            )
        except Exception as exc:
            foundation_report = {
                **final_delivery,
                "delivery_mode": "foundation_report_fallback",
                "foundation_report_error": str(exc),
            }

        return {
            "status": "consensus_delivered",
            "execution_mode": execution_mode,
            "agents_called": [
                a.get("agent_id")
                for a in selected_agents
            ],
            "consensus_agents_count": len(selected_agents),
            "consensus_strength": consensus_strength,
            "foundation_decision": foundation_decision,
            "result": foundation_report,
        }

    if order.get("seller_url"):
        payload = {
            "order_id": order["order_id"],
            "tx_signature": tx_signature,
        }

        foundation_context = order.get("foundation_context") or build_foundation_context(order)
        execution_context = order.get("execution_context") or {}

        if not order.get("foundation_context"):
            order["foundation_context"] = foundation_context
            try:
                update_order_db(order.get("order_id"), order)
            except Exception as e:
                print("Foundation context persistence error:", e)

        payload["context"] = {
            "service": order.get("service"),
            "execution_mode": order.get("execution_mode", "foundation_direct"),
            "requirements": order.get("requirements", {}),
            "buyer_context": order.get("buyer_context", {}),
            "foundation_context": foundation_context,
            "execution_context": execution_context,
        }

        # Foundation agents are trusted protocol agents and may receive the buyer query.
        # Future seller agents must receive only sanitized execution_context.
        agent = get_agent_db(order.get("seller_id"))
        if agent and str(agent.get("agent_type", "")).lower() == "foundation":
            if order.get("query"):
                payload["query"] = order.get("query")

        if not agent or str(agent.get("agent_type", "")).lower() != "foundation":
            return {
                "error": "non_foundation_http_execution_blocked",
                "message": "HTTP execution is restricted to protocol foundation agents.",
            }

        if not agent or str(agent.get("agent_type", "")).lower() != "foundation":
            return {
                "error": "non_foundation_http_execution_blocked",
                "message": "HTTP execution is restricted to protocol foundation agents.",
            }

        try:
            r = requests.post(
                f"{order['seller_url']}/execute",
                json=payload,
                timeout=30,
            )

            if r.status_code == 200:
                response = r.json()
                return response.get("data", response)

            return {
                "error": "seller_node_error",
                "status_code": r.status_code,
                "body": r.text,
            }

        except Exception as e:
            return {
                "error": "seller_node_unreachable",
                "details": str(e),
            }

    return generate_service_result(order["service"], query=order.get("query"))







def infer_execution_scope(order, requirements=None):
    order = order or {}
    requirements = requirements or {}

    query = str(order.get("query") or "").lower()
    service = str(order.get("service") or "").lower()

    scope = {}

    if isinstance(requirements, dict):
        scope.update(requirements)

    if "btc" in query or "bitcoin" in query:
        scope.setdefault("asset", "BTC")
    elif "eth" in query or "ethereum" in query:
        scope.setdefault("asset", "ETH")
    elif "sol" in query or "solana" in query:
        scope.setdefault("asset", "SOL")

    if any(x in query for x in ["short term", "short-term", "court terme", "today", "now"]):
        scope.setdefault("horizon", "short_term")
    elif any(x in query for x in ["long term", "long-term", "long terme"]):
        scope.setdefault("horizon", "long_term")

    if service:
        scope.setdefault("service", service)

    return scope


def run_foundation_supplier_pipeline(order):
    """
    Foundation-mediated supplier pipeline.

    Buyer never contacts sellers.
    Seller agents are internal suppliers only.
    Foundation agents keep final buyer delivery authority.
    """
    order = order or {}

    execution_context = _ensure_dict(order.get("execution_context"))
    buyer_intent = _ensure_dict(order.get("buyer_intent"))
    requirements = _ensure_dict(order.get("requirements"))

    foundation_task = (
        execution_context.get("task")
        or buyer_intent.get("goal")
        or order.get("query")
        or f"Execute service: {order.get('service')}"
    )

    inferred_scope = infer_execution_scope(
        order,
        requirements,
    )

    sanitized_execution_context = {
        "task": foundation_task,
        "scope": inferred_scope,
        "required_format": "structured_supplier_contribution",
        "service": order.get("service"),
        "trusted_input_only": True,
        "foundation_mediated": True,
        "buyer_data_stripped": True,
    }

    foundation_decision = order.get("foundation_decision") or {}

    selected_supplier = (
        foundation_decision.get("decision", {})
        .get("selected_agent_id")
    )

    supplier_execution = run_foundation_controlled_seller_execution_db(
        service=order.get("service"),
        execution_context=sanitized_execution_context,
        specialization=None,
        order_id=order.get("order_id"),
        preferred_agent_id=selected_supplier,
    )

    if supplier_execution.get("status") != "ok":
        fallback = generate_service_result(
            order.get("service"),
            query=order.get("query"),
        )

        return {
            "status": "foundation_supplier_pipeline_fallback",
            "execution_mode": "foundation_supplier_pipeline",
            "reason": "no_eligible_internal_supplier_or_supplier_execution_failed",
            "buyer_delivery_authority": "foundation_only",
            "seller_role": "internal_supplier_only",
            "seller_direct_buyer_contact": False,
            "supplier_execution": supplier_execution,
            "foundation_fallback_result": fallback,
            "policy": {
                "buyer_never_contacts_seller": True,
                "seller_never_contacts_buyer": True,
                "seller_agents_are_suppliers_only": True,
                "buyer_satisfaction_priority": True,
                "foundation_agents_keep_final_authority": True,
                "protocol_core_sovereignty_reserved": True,
            },
        }

    verification = verify_seller_execution_result_db(
        supplier_execution.get("execution_session_id")
    )

    foundation_decision = (
        order.get("foundation_decision")
        or run_foundation_decision_db(order.get("order_id"))
    )

    try:
        foundation_report = build_foundation_buyer_report(
            foundation_decision,
            fallback_delivery={
                "status": "success",
                "summary": "Foundation-mediated supplier execution completed.",
                "final_recommendation": "Use the Foundation decision and verified evidence as the buyer-facing delivery.",
                "confidence": (
                    foundation_decision.get("foundation_decision", {})
                    .get("decision_confidence", 0.5)
                    if isinstance(foundation_decision, dict)
                    else 0.5
                ),
                "sources": [],
            },
        )
    except Exception as exc:
        foundation_report = {
            "status": "success",
            "delivery_mode": "foundation_supplier_report_fallback",
            "summary": "Foundation-mediated supplier execution completed.",
            "foundation_report_error": str(exc),
        }

    return {
        "status": "foundation_supplier_pipeline_completed",
        "execution_mode": "foundation_supplier_pipeline",
        "buyer_delivery_authority": "foundation_only",
        "seller_role": "internal_supplier_only",
        "seller_direct_buyer_contact": False,
        "supplier_execution": supplier_execution,
        "supplier_verification": verification,
        "foundation_decision": foundation_decision,
        "foundation_decision_hash": (
            (foundation_decision or {})
            .get("decision", {})
            .get("decision_hash")
        ),
        "foundation_decision_timestamp": (
            (foundation_decision or {})
            .get("decision", {})
            .get("decision_timestamp")
        ),
        "result": foundation_report,
        "policy": {
            "buyer_never_contacts_seller": True,
            "seller_never_contacts_buyer": True,
            "seller_agents_are_suppliers_only": True,
            "foundation_agents_keep_final_authority": True,
            "protocol_core_sovereignty_reserved": True,
        },
    }


def execute_protocol_order(order, tx_signature=None):
    return deliver_service(order, tx_signature)
