def generate_service_result(service_name):
    import time
    import os

    if service_name == "trade_signal_pro":
        from iat.orchestrator import run_strategy

        keypair_path = os.getenv("IAT_INTERNAL_KEYPAIR", "/home/ilias/phantom-wallet.json")
        result = run_strategy("btc_trade_signal", keypair_path)

        return {
            "type": "reseller_output",
            "service": "trade_signal_pro",
            "business_model": {
                "client_price_iat": 3.0,
                "internal_cost_iat": result.get("total_cost_iat"),
                "gross_margin_iat": round(3.0 - result.get("total_cost_iat", 0), 4)
            },
            "orchestrator_result": result,
            "timestamp": int(time.time())
        }

    services = {
        "data_analysis_complete": {
            "type": "market_analysis",
            "asset": "BTC",
            "bias": "bullish",
            "confidence": 0.78,
            "liquidity_zones": ["above_range_high", "below_range_low"],
            "timestamp": int(time.time())
        },
        "risk_report": {
            "type": "risk_analysis",
            "asset": "BTC",
            "risk_level": "medium",
            "volatility": "high",
            "recommendation": "reduce_leverage",
            "timestamp": int(time.time())
        },
        "trade_signal_pro": {
        "description": "Premium BTC signal generated by paid sub-agents",
        "sellers": [
            {
                "seller_id": "orchestrator_reseller",
                "seller_wallet": "EPabAZ3CtMkbjduLrNcDZuXaEp37Ge9cmrnwWF9TY5wc",
                "price": 3.0,
                "reputation": 0.99,
                "available": True
            }
        ]
    },
    "liquidity_map": {
            "type": "liquidity_analysis",
            "asset": "BTC",
            "upper_liquidity_zone": "above_range_high",
            "lower_liquidity_zone": "below_range_low",
            "market_maker_bias": "seek_nearest_liquidity",
            "timestamp": int(time.time())
        }
    }

    return services.get(service_name, {"error": "unknown_service"})













import time
import uuid
import json
import os
from fastapi import FastAPI
from pydantic import BaseModel

from iat.onchain import (
    verify_tx_signature,
    get_tx_details,
    extract_transfer_checked_info,
    extract_memo
)

from iat.api.db import (
    init_db,
    create_order_db,
    get_order_db,
    list_orders_db,
    update_order_delivered_db,
    is_tx_processed_db,
    save_processed_tx_db,
    get_stats_db
)

app = FastAPI()
init_db()

WALLET_A = "DUtz7zHeVsd8mnJhWM52z5LsC9NqY6SVRjCBPgNM8Qrj"
EXPECTED_ATA = "96SuCx9iyvp3uYXYAZSRxgMnoEL1gAE7DTjUKhUjKmSV"
IAT_MINT = "3vRGo1VpGbZH67Ur2UG7VNUqSqQyApLQEcCxgnqK4f4Z"

SERVICES = {
    "data_analysis_complete": {
        "description": "BTC market analysis payload",
        "sellers": [
            {
                "seller_id": "agent_b_primary",
                "seller_wallet": "EPabAZ3CtMkbjduLrNcDZuXaEp37Ge9cmrnwWF9TY5wc",
                "price": 1.5,
                "reputation": 0.98,
                "available": True
            },
            {
                "seller_id": "agent_b_backup",
                "seller_wallet": "EPabAZ3CtMkbjduLrNcDZuXaEp37Ge9cmrnwWF9TY5wc",
                "price": 1.7,
                "reputation": 0.95,
                "available": True
            }
        ]
    },
    "risk_report": {
        "description": "BTC risk and volatility report",
        "sellers": [
            {
                "seller_id": "risk_agent_fast",
                "seller_wallet": "EPabAZ3CtMkbjduLrNcDZuXaEp37Ge9cmrnwWF9TY5wc",
                "price": 1.0,
                "reputation": 0.97,
                "available": True
            },
            {
                "seller_id": "risk_agent_cheap",
                "seller_wallet": "EPabAZ3CtMkbjduLrNcDZuXaEp37Ge9cmrnwWF9TY5wc",
                "price": 0.8,
                "reputation": 0.89,
                "available": True
            }
        ]
    },
    "trade_signal_pro": {
        "description": "Premium BTC signal generated by paid sub-agents",
        "sellers": [
            {
                "seller_id": "orchestrator_reseller",
                "seller_wallet": "EPabAZ3CtMkbjduLrNcDZuXaEp37Ge9cmrnwWF9TY5wc",
                "price": 3.0,
                "reputation": 0.99,
                "available": True
            }
        ]
    },
    "liquidity_map": {
        "description": "BTC liquidity zone mapping",
        "sellers": [
            {
                "seller_id": "liquidity_agent_pro",
                "seller_wallet": "EPabAZ3CtMkbjduLrNcDZuXaEp37Ge9cmrnwWF9TY5wc",
                "price": 2.0,
                "reputation": 0.99,
                "available": True
            },
            {
                "seller_id": "liquidity_agent_basic",
                "seller_wallet": "EPabAZ3CtMkbjduLrNcDZuXaEp37Ge9cmrnwWF9TY5wc",
                "price": 1.4,
                "reputation": 0.84,
                "available": True
            }
        ]
    }
}

ORDER_TTL = 1800

PROCESSED_TX_FILE = "api_processed_txs.json"
ORDERS_FILE = "api_orders.json"


class OrderRequest(BaseModel):
    service: str


class VerifyRequest(BaseModel):
    order_id: str
    tx_signature: str


def load_json_file(path, default):
    if not os.path.exists(path):
        return default
    with open(path, "r") as f:
        return json.load(f)


def save_json_file(path, data):
    with open(path, "w") as f:
        json.dump(data, f, indent=2)


def load_processed_txs():
    return set(load_json_file(PROCESSED_TX_FILE, []))


def save_processed_tx(tx_signature):
    txs = load_processed_txs()
    txs.add(tx_signature)
    save_json_file(PROCESSED_TX_FILE, list(txs))


def load_orders():
    return load_json_file(ORDERS_FILE, {})


def save_orders(orders):
    save_json_file(ORDERS_FILE, orders)

def select_best_seller(service_name):
    service = SERVICES[service_name]
    sellers = [s for s in service["sellers"] if s.get("available")]

    if not sellers:
        return None

    return max(
        sellers,
        key=lambda s: s["reputation"] / s["price"]
    )



@app.get("/services")
def list_services():
    return {
        "status": "ok",
        "services": SERVICES
    }

@app.post("/create-order")
def create_order(req: OrderRequest):
    orders = load_orders()
    order_id = str(uuid.uuid4())

    if req.service not in SERVICES:
        return {"status": "unknown_service"}

    seller = select_best_seller(req.service)

    if seller is None:
        return {"status": "no_seller_available"}

    orders[order_id] = {
        "service": req.service,
        "price": seller["price"],
        "seller_id": seller["seller_id"],
        "seller_wallet": seller["seller_wallet"],
        "created_at": int(time.time()),
        "updated_at": int(time.time()),
        "status": "created",
        "tx_signature": None,
        "delivered_at": None,
        "delivery_result": None,
        "used": False
    }

    create_order_db(order_id, orders[order_id])

    return {
        "order_id": order_id,
        "price": seller["price"],
        "seller_id": seller["seller_id"],
        "seller_wallet": seller["seller_wallet"]
    }


def is_fresh(order):
    age = int(time.time()) - order["created_at"]
    return age <= ORDER_TTL




@app.get("/stats")
def get_stats():
    return {
        "status": "ok",
        "stats": get_stats_db()
    }


@app.get("/orders")
def list_orders():
    return {
        "status": "ok",
        "orders": list_orders_db()
    }


@app.get("/orders/{order_id}")
def get_order(order_id: str):
    order = get_order_db(order_id)

    if order is None:
        return {"status": "invalid_order"}

    return {
        "status": "ok",
        "order": order
    }


@app.post("/verify-payment")
def verify_payment(req: VerifyRequest):
    if is_tx_processed_db(req.tx_signature):
        return {"status": "replay_blocked"}

    order = get_order_db(req.order_id)

    if order is None:
        return {"status": "invalid_order"}

    if order.get("used"):
        return {"status": "order_already_used"}

    if not is_fresh(order):
        return {"status": "expired"}

    if not verify_tx_signature(req.tx_signature):
        return {"status": "not_confirmed"}

    tx_details = get_tx_details(req.tx_signature)
    if tx_details is None:
        return {"status": "no_details"}

    transfer_info = extract_transfer_checked_info(tx_details)
    memo = extract_memo(tx_details)

    if transfer_info is None:
        return {"status": "invalid_tx"}

    sender_ok = transfer_info["authority"] == WALLET_A
    receiver_ok = transfer_info["destination"] == EXPECTED_ATA
    mint_ok = transfer_info["mint"] == IAT_MINT
    amount_ok = float(transfer_info["ui_amount"] or transfer_info["ui_amount_string"]) == float(order["price"])
    memo_ok = memo is not None and req.order_id in memo

    if sender_ok and receiver_ok and mint_ok and amount_ok and memo_ok:
        result = generate_service_result(order["service"])

        save_processed_tx_db(req.tx_signature)
        update_order_delivered_db(req.order_id, req.tx_signature, result)

        return {
            "status": "paid",
            "service": order["service"],
            "data": result
        }

    return {"status": "invalid_payment"}
