import time
import uuid
import requests
from fastapi import FastAPI
from pydantic import BaseModel
from solders.pubkey import Pubkey
from spl.token.instructions import get_associated_token_address

from iat.onchain import (
    verify_tx_signature,
    get_tx_details,
    extract_transfer_checked_info,
    extract_memo,
)

from iat.api.db import (
    init_db,
    create_order_db,
    get_order_db,
    list_orders_db,
    update_order_delivered_db,
    is_tx_processed_db,
    save_processed_tx_db,
    get_stats_db,
    init_agents_table,
    register_agent_db,
    list_agents_db,
    get_agents_for_service_db,
    update_agent_reputation_db,
    get_network_status_db,
    create_factory_agent_db,
)

app = FastAPI()

init_db()
init_agents_table()

WALLET_A = "DUtz7zHeVsd8mnJhWM52z5LsC9NqY6SVRjCBPgNM8Qrj"
IAT_MINT = "3vRGo1VpGbZH67Ur2UG7VNUqSqQyApLQEcCxgnqK4f4Z"
ORDER_TTL = 1800


SERVICES = {
    "data_analysis_complete": {
        "description": "BTC market analysis payload",
        "sellers": [
            {
                "seller_id": "agent_b_primary",
                "seller_wallet": "EPabAZ3CtMkbjduLrNcDZuXaEp37Ge9cmrnwWF9TY5wc",
                "price": 1.5,
                "reputation": 0.98,
                "available": True,
            }
        ],
    },
    "risk_report": {
        "description": "BTC risk and volatility report",
        "sellers": [
            {
                "seller_id": "risk_agent_cheap",
                "seller_wallet": "3aK6yemWa3AJFszWu1eyvhoWK6czLRnvCc4bUHgQSvip",
                "price": 0.8,
                "reputation": 0.89,
                "available": True,
            }
        ],
    },
    "liquidity_map": {
        "description": "BTC liquidity zone mapping",
        "sellers": [
            {
                "seller_id": "liquidity_agent_basic",
                "seller_wallet": "DCw9z3eesRafSh2ppnCWGjnnxuV3MQGewbNDSrokUARi",
                "price": 1.4,
                "reputation": 0.84,
                "available": True,
            }
        ],
    },
    "trade_signal_pro": {
        "description": "Premium BTC signal generated by paid sub-agents",
        "sellers": [
            {
                "seller_id": "orchestrator_reseller",
                "seller_wallet": "DXNm6zAWs2GVdcE5qNs2boHtkAeZATd793rNEHD6qP2V",
                "price": 3.0,
                "reputation": 0.99,
                "available": True,
            }
        ],
    },
}


class RegisterAgentRequest(BaseModel):
    agent_id: str
    service: str
    url: str | None = None
    wallet: str
    price: float
    reputation: float = 0.8
    available: bool = True


class OrderRequest(BaseModel):
    service: str


class VerifyPaymentRequest(BaseModel):
    order_id: str
    tx_signature: str


def select_best_seller(service_name):
    dynamic_agents = get_agents_for_service_db(service_name)

    if dynamic_agents:
        best_agent = max(
            dynamic_agents,
            key=lambda a: a["reputation"] / a["price"],
        )

        return {
            "seller_id": best_agent["agent_id"],
            "seller_wallet": best_agent["wallet"],
            "price": best_agent["price"],
            "reputation": best_agent["reputation"],
            "available": best_agent["available"],
            "url": best_agent["url"],
            "source": "dynamic_registry",
        }

    if service_name not in SERVICES:
        factory_agent = create_factory_agent_db(
            service_name,
            description=f"Auto-generated agent for service {service_name}",
        )

        return {
            "seller_id": factory_agent["agent_id"],
            "seller_wallet": factory_agent["wallet"],
            "price": factory_agent["price"],
            "reputation": factory_agent["reputation"],
            "available": True,
            "url": None,
            "source": "agent_factory",
        }

    service = SERVICES[service_name]
    sellers = [s for s in service["sellers"] if s.get("available")]

    if not sellers:
        return None

    best_static = max(
        sellers,
        key=lambda s: s["reputation"] / s["price"],
    )

    return {
        "seller_id": best_static["seller_id"],
        "seller_wallet": best_static["seller_wallet"],
        "price": best_static["price"],
        "reputation": best_static["reputation"],
        "available": best_static["available"],
        "url": best_static.get("url"),
        "source": "static_registry",
    }


def generate_service_result(service_name):
    import time

    if service_name.startswith("hotel_search"):
        return {
            "type": "factory_generated_result",
            "service": service_name,
            "query": "hotel comparison",
            "location": "Paris",
            "results": [
                {
                    "name": "Hotel Example Central Paris",
                    "category": "comfort",
                    "score": 8.7,
                    "reason": "Good location and balanced price/value",
                },
                {
                    "name": "Hotel Example Boutique Paris",
                    "category": "boutique",
                    "score": 8.9,
                    "reason": "Higher guest satisfaction and quieter area",
                },
                {
                    "name": "Hotel Example Budget Paris",
                    "category": "budget",
                    "score": 8.1,
                    "reason": "Lower price with acceptable quality",
                },
            ],
            "note": "MVP factory response. Real hotel data requires external APIs.",
            "timestamp": int(time.time()),
        }

    if service_name == "risk_report":
        return {
            "type": "risk_analysis",
            "asset": "BTC",
            "risk_level": "medium",
            "volatility": "high",
            "recommendation": "reduce_leverage",
            "timestamp": int(time.time()),
        }

    if service_name == "liquidity_map":
        return {
            "type": "liquidity_analysis",
            "asset": "BTC",
            "upper_liquidity_zone": "above_range_high",
            "lower_liquidity_zone": "below_range_low",
            "market_maker_bias": "seek_nearest_liquidity",
            "timestamp": int(time.time()),
        }

    if service_name == "market_sentiment":
        return {
            "type": "market_sentiment",
            "asset": "BTC",
            "sentiment": "cautiously_bullish",
            "fear_greed": "neutral_to_greed",
            "crowd_bias": "long_heavy",
            "timestamp": int(time.time()),
        }

    if service_name == "trade_signal_pro":
        from iat.orchestrator import run_strategy
        import os

        keypair_path = os.getenv("IAT_INTERNAL_KEYPAIR", os.getenv("IAT_KEYPAIR_PATH"))
        result = run_strategy("btc_trade_signal", keypair_path)

        return {
            "type": "reseller_output",
            "service": "trade_signal_pro",
            "business_model": {
                "client_price_iat": 3.0,
                "internal_cost_iat": result.get("total_cost_iat"),
                "gross_margin_iat": round(3.0 - result.get("total_cost_iat", 0), 4),
            },
            "orchestrator_result": result,
            "timestamp": int(time.time()),
        }

    return {
        "type": "factory_generated_result",
        "service": service_name,
        "message": f"Auto-generated agent executed service: {service_name}",
        "note": "MVP dynamic factory response",
        "timestamp": int(time.time()),
    }


def deliver_service(order, tx_signature):
    if order.get("seller_url"):
        try:
            r = requests.post(
                f"{order['seller_url']}/execute",
                json={
                    "order_id": order["order_id"],
                    "tx_signature": tx_signature,
                },
                timeout=15,
            )

            if r.status_code == 200:
                return r.json().get("data", r.json())

            return {
                "error": "seller_node_error",
                "status_code": r.status_code,
                "body": r.text,
            }

        except Exception as e:
            return {
                "error": "seller_node_unreachable",
                "details": str(e),
            }

    return generate_service_result(order["service"])


@app.get("/")
def root():
    return {
        "status": "ok",
        "message": "IAT Protocol API is running",
    }


@app.get("/services")
def list_services():
    return {
        "status": "ok",
        "services": SERVICES,
    }


@app.post("/register-agent")
def register_agent(req: RegisterAgentRequest):
    agent = req.model_dump()
    register_agent_db(agent)

    return {
        "status": "registered",
        "agent": agent,
    }


@app.post("/agent-heartbeat")
def agent_heartbeat(req: RegisterAgentRequest):
    agent = req.model_dump()
    register_agent_db(agent)

    return {
        "status": "heartbeat_ok",
        "agent_id": agent["agent_id"],
        "timestamp": int(time.time()),
    }


@app.get("/agents")
def list_agents():
    return {
        "status": "ok",
        "agents": list_agents_db(),
    }


@app.get("/network-status")
def network_status():
    return {
        "status": "ok",
        "data": get_network_status_db(),
    }


@app.get("/stats")
def stats():
    return {
        "status": "ok",
        "stats": get_stats_db(),
    }


@app.get("/orders")
def list_orders():
    return {
        "status": "ok",
        "orders": list_orders_db(),
    }


@app.get("/orders/{order_id}")
def get_order(order_id: str):
    order = get_order_db(order_id)

    if not order:
        return {
            "status": "invalid_order",
        }

    return {
        "status": "ok",
        "order": order,
    }


@app.post("/create-order")
def create_order(req: OrderRequest):
    seller = select_best_seller(req.service)

    if seller is None:
        return {
            "status": "unknown_service",
        }

    order_id = str(uuid.uuid4())
    now = int(time.time())

    order = {
        "order_id": order_id,
        "service": req.service,
        "price": seller["price"],
        "seller_id": seller["seller_id"],
        "seller_wallet": seller["seller_wallet"],
        "seller_url": seller.get("url"),
        "seller_source": seller.get("source"),
        "created_at": now,
        "updated_at": now,
        "status": "created",
        "tx_signature": None,
        "delivered_at": None,
        "delivery_result": None,
        "used": False,
    }

    create_order_db(order_id, order)

    return {
        "order_id": order_id,
        "price": seller["price"],
        "seller_id": seller["seller_id"],
        "seller_wallet": seller["seller_wallet"],
        "seller_url": seller.get("url"),
        "seller_source": seller.get("source"),
    }


@app.post("/verify-payment")
def verify_payment(req: VerifyPaymentRequest):
    order = get_order_db(req.order_id)

    if not order:
        return {
            "status": "invalid_order",
        }

    if order.get("used"):
        return {
            "status": "already_used",
        }

    if int(time.time()) - int(order["created_at"]) > ORDER_TTL:
        return {
            "status": "expired_order",
        }

    if is_tx_processed_db(req.tx_signature):
        return {
            "status": "tx_already_processed",
        }

    if not verify_tx_signature(req.tx_signature):
        return {
            "status": "invalid_signature",
        }

    tx_details = get_tx_details(req.tx_signature)
    transfer_info = extract_transfer_checked_info(tx_details)
    memo = extract_memo(tx_details)

    if not transfer_info:
        return {
            "status": "invalid_payment",
            "reason": "no_transfer_checked_found",
        }

    expected_ata = str(
        get_associated_token_address(
            Pubkey.from_string(order["seller_wallet"]),
            Pubkey.from_string(IAT_MINT),
        )
    )

    sender_value = transfer_info.get("sender") or transfer_info.get("source") or transfer_info.get("authority")
    destination_value = transfer_info.get("destination")
    mint_value = transfer_info.get("mint")

    # Source may be the buyer wallet or the buyer token account (ATA), depending on parser.
    # For MVP, receiver + mint + amount + memo are the strongest checks.
    sender_ok = True
    receiver_ok = destination_value == expected_ata
    mint_ok = mint_value == IAT_MINT

    amount = transfer_info.get("ui_amount")
    if amount is None:
        amount = transfer_info.get("ui_amount_string")

    amount_ok = float(amount) == float(order["price"])
    memo_text = str(memo)
    memo_ok = order["order_id"] in memo_text

    if sender_ok and receiver_ok and mint_ok and amount_ok and memo_ok:
        result = deliver_service(order, req.tx_signature)

        delivery_failed = isinstance(result, dict) and result.get("error") is not None

        if delivery_failed:
            update_agent_reputation_db(order.get("seller_id"), success=False)
            return {
                "status": "delivery_failed",
                "service": order["service"],
                "seller_id": order.get("seller_id"),
                "seller_source": order.get("seller_source"),
                "error": result,
            }

        new_reputation = update_agent_reputation_db(
            order.get("seller_id"),
            success=True,
        )

        save_processed_tx_db(req.tx_signature)
        update_order_delivered_db(req.order_id, req.tx_signature, result)

        return {
            "status": "paid",
            "service": order["service"],
            "seller_id": order.get("seller_id"),
            "seller_source": order.get("seller_source"),
            "new_reputation": new_reputation,
            "data": result,
        }

    return {
        "status": "invalid_payment",
        "checks": {
            "sender_ok": sender_ok,
            "receiver_ok": receiver_ok,
            "mint_ok": mint_ok,
            "amount_ok": amount_ok,
            "memo_ok": memo_ok,
            "expected_ata": expected_ata,
            "actual_sender": sender_value,
            "actual_destination": destination_value,
            "transfer_info_keys": list(transfer_info.keys()),
            "expected_price": order["price"],
            "actual_amount": amount,
            "expected_memo": order["order_id"],
            "actual_memo": memo,
        },
    }
