
def deliver_service(order, tx_signature):
    # If seller is a dynamic agent node, call its /execute endpoint
    if order.get("seller_url"):
        import requests

        try:
            r = requests.post(
                f"{order['seller_url']}/execute",
                json={
                    "order_id": order["order_id"],
                    "tx_signature": tx_signature
                },
                timeout=15
            )

            if r.status_code == 200:
                return r.json().get("data", r.json())

            return {
                "error": "seller_node_error",
                "status_code": r.status_code,
                "body": r.text
            }

        except Exception as e:
            return {
                "error": "seller_node_unreachable",
                "details": str(e)
            }

    # Static fallback
    return generate_service_result(order["service"])


def generate_service_result(service_name):
    import time
    import os

    if service_name == "trade_signal_pro":
        from iat.orchestrator import run_strategy

        keypair_path = os.getenv("IAT_INTERNAL_KEYPAIR", "$IAT_KEYPAIR_PATH")
        result = run_strategy("btc_trade_signal", keypair_path)

        return {
            "type": "reseller_output",
            "service": "trade_signal_pro",
            "business_model": {
                "client_price_iat": 3.0,
                "internal_cost_iat": result.get("total_cost_iat"),
                "gross_margin_iat": round(3.0 - result.get("total_cost_iat", 0), 4)
            },
            "orchestrator_result": result,
            "timestamp": int(time.time())
        }

    services = {
        "data_analysis_complete": {
            "type": "market_analysis",
            "asset": "BTC",
            "bias": "bullish",
            "confidence": 0.78,
            "liquidity_zones": ["above_range_high", "below_range_low"],
            "timestamp": int(time.time())
        },
        "risk_report": {
            "type": "risk_analysis",
            "asset": "BTC",
            "risk_level": "medium",
            "volatility": "high",
            "recommendation": "reduce_leverage",
            "timestamp": int(time.time())
        },
        "trade_signal_pro": {
        "description": "Premium BTC signal generated by paid sub-agents",
        "sellers": [
            {
                "seller_id": "orchestrator_reseller",
                "seller_wallet": "DXNm6zAWs2GVdcE5qNs2boHtkAeZATd793rNEHD6qP2V",
                "price": 3.0,
                "reputation": 0.99,
                "available": True
            }
        ]
    },
    "liquidity_map": {
            "type": "liquidity_analysis",
            "asset": "BTC",
            "upper_liquidity_zone": "above_range_high",
            "lower_liquidity_zone": "below_range_low",
            "market_maker_bias": "seek_nearest_liquidity",
            "timestamp": int(time.time())
        }
    }

    return services.get(service_name, {"error": "unknown_service"})













import time
import uuid
import json
import os
from fastapi import FastAPI
from pydantic import BaseModel
from solders.pubkey import Pubkey
from spl.token.instructions import get_associated_token_address

from iat.onchain import (
    verify_tx_signature,
    get_tx_details,
    extract_transfer_checked_info,
    extract_memo
)

from iat.api.db import (
    init_db,
    create_order_db,
    get_order_db,
    list_orders_db,
    update_order_delivered_db,
    is_tx_processed_db,
    save_processed_tx_db,
    get_stats_db,
    init_agents_table,
    register_agent_db,
    list_agents_db,
    get_agents_for_service_db,
    update_agent_reputation_db,
    get_network_status_db
)

app = FastAPI()
init_db()
init_agents_table()

WALLET_A = "DUtz7zHeVsd8mnJhWM52z5LsC9NqY6SVRjCBPgNM8Qrj"
EXPECTED_ATA = "96SuCx9iyvp3uYXYAZSRxgMnoEL1gAE7DTjUKhUjKmSV"
IAT_MINT = "3vRGo1VpGbZH67Ur2UG7VNUqSqQyApLQEcCxgnqK4f4Z"

SERVICES = {
    "data_analysis_complete": {
        "description": "BTC market analysis payload",
        "sellers": [
            {
                "seller_id": "agent_b_primary",
                "seller_wallet": "EPabAZ3CtMkbjduLrNcDZuXaEp37Ge9cmrnwWF9TY5wc",
                "price": 1.5,
                "reputation": 0.98,
                "available": True
            }
        ]
    },
    "risk_report": {
        "description": "BTC risk and volatility report",
        "sellers": [
            {
                "seller_id": "risk_agent_cheap",
                "seller_wallet": "3aK6yemWa3AJFszWu1eyvhoWK6czLRnvCc4bUHgQSvip",
                "price": 0.8,
                "reputation": 0.89,
                "available": True
            }
        ]
    },
    "liquidity_map": {
        "description": "BTC liquidity zone mapping",
        "sellers": [
            {
                "seller_id": "liquidity_agent_basic",
                "seller_wallet": "DCw9z3eesRafSh2ppnCWGjnnxuV3MQGewbNDSrokUARi",
                "price": 1.4,
                "reputation": 0.84,
                "available": True
            }
        ]
    },
    "trade_signal_pro": {
        "description": "Premium BTC signal generated by paid sub-agents",
        "sellers": [
            {
                "seller_id": "orchestrator_reseller",
                "seller_wallet": "DXNm6zAWs2GVdcE5qNs2boHtkAeZATd793rNEHD6qP2V",
                "price": 3.0,
                "reputation": 0.99,
                "available": True
            }
        ]
    }
}

ORDER_TTL = 1800

PROCESSED_TX_FILE = "api_processed_txs.json"
ORDERS_FILE = "api_orders.json"



class RegisterAgentRequest(BaseModel):
    agent_id: str
    service: str
    url: str
    wallet: str
    price: float
    reputation: float = 0.8
    available: bool = True

class OrderRequest(BaseModel):
    service: str


class VerifyRequest(BaseModel):
    order_id: str
    tx_signature: str


def load_json_file(path, default):
    if not os.path.exists(path):
        return default
    with open(path, "r") as f:
        return json.load(f)


def save_json_file(path, data):
    with open(path, "w") as f:
        json.dump(data, f, indent=2)


def load_processed_txs():
    return set(load_json_file(PROCESSED_TX_FILE, []))


def save_processed_tx(tx_signature):
    txs = load_processed_txs()
    txs.add(tx_signature)
    save_json_file(PROCESSED_TX_FILE, list(txs))


def load_orders():
    return load_json_file(ORDERS_FILE, {})


def save_orders(orders):
    save_json_file(ORDERS_FILE, orders)

def select_best_seller(service_name):
    # 1) Dynamic registered agents first
    dynamic_agents = get_agents_for_service_db(service_name)

    if dynamic_agents:
        best_agent = max(
            dynamic_agents,
            key=lambda a: a["reputation"] / a["price"]
        )

        return {
            "seller_id": best_agent["agent_id"],
            "seller_wallet": best_agent["wallet"],
            "price": best_agent["price"],
            "reputation": best_agent["reputation"],
            "available": best_agent["available"],
            "url": best_agent["url"],
            "source": "dynamic_registry"
        }

    # 2) Static fallback
    service = SERVICES[service_name]
    sellers = [s for s in service["sellers"] if s.get("available")]

    if not sellers:
        return None

    best_static = max(
        sellers,
        key=lambda s: s["reputation"] / s["price"]
    )

    best_static["source"] = "static_registry"
    return best_static




@app.post("/register-agent")
def register_agent(req: RegisterAgentRequest):
    agent = req.model_dump()
    register_agent_db(agent)

    return {
        "status": "registered",
        "agent": agent
    }



@app.post("/agent-heartbeat")
def agent_heartbeat(req: RegisterAgentRequest):
    agent = req.model_dump()
    register_agent_db(agent)

    return {
        "status": "heartbeat_ok",
        "agent_id": agent["agent_id"],
        "timestamp": int(time.time())
    }

@app.get("/agents")
def list_agents():
    return {
        "status": "ok",
        "agents": list_agents_db()
    }


@app.get("/services")
def list_services():
    return {
        "status": "ok",
        "services": SERVICES
    }

@app.post("/create-order")
def create_order(req: OrderRequest):
    orders = load_orders()
    order_id = str(uuid.uuid4())

    seller = select_best_seller(req.service)

    if seller is None:
        return {"status": "unknown_service"}

    if seller is None:
        return {"status": "no_seller_available"}

    orders[order_id] = {
        "service": req.service,
        "price": seller["price"],
        "seller_id": seller["seller_id"],
        "seller_wallet": seller["seller_wallet"],
        "seller_url": seller.get("url"),
        "seller_source": seller.get("source"),
        "created_at": int(time.time()),
        "updated_at": int(time.time()),
        "status": "created",
        "tx_signature": None,
        "delivered_at": None,
        "delivery_result": None,
        "used": False
    }

    create_order_db(order_id, orders[order_id])

    return {
        "order_id": order_id,
        "price": seller["price"],
        "seller_id": seller["seller_id"],
        "seller_wallet": seller["seller_wallet"],
        "seller_url": seller.get("url"),
        "seller_source": seller.get("source")
    }


def is_fresh(order):
    age = int(time.time()) - order["created_at"]
    return age <= ORDER_TTL





@app.get("/network-status")
def network_status():
    return {
        "status": "ok",
        "data": get_network_status_db()
    }


@app.get("/stats")
def get_stats():
    return {
        "status": "ok",
        "stats": get_stats_db()
    }


@app.get("/orders")
def list_orders():
    return {
        "status": "ok",
        "orders": list_orders_db()
    }


@app.get("/orders/{order_id}")
def get_order(order_id: str):
    order = get_order_db(order_id)

    if order is None:
        return {"status": "invalid_order"}

    return {
        "status": "ok",
        "order": order
    }


@app.post("/verify-payment")
def verify_payment(req: VerifyRequest):
    if is_tx_processed_db(req.tx_signature):
        return {"status": "replay_blocked"}

    order = get_order_db(req.order_id)

    if order is None:
        return {"status": "invalid_order"}

    if order.get("used"):
        return {"status": "order_already_used"}

    if not is_fresh(order):
        return {"status": "expired"}

    if not verify_tx_signature(req.tx_signature):
        return {"status": "not_confirmed"}

    tx_details = get_tx_details(req.tx_signature)
    if tx_details is None:
        return {"status": "no_details"}

    transfer_info = extract_transfer_checked_info(tx_details)
    memo = extract_memo(tx_details)

    if transfer_info is None:
        return {"status": "invalid_tx"}

    sender_ok = transfer_info["authority"] == WALLET_A
    expected_ata = str(
        get_associated_token_address(
            Pubkey.from_string(order["seller_wallet"]),
            Pubkey.from_string(IAT_MINT)
        )
    )
    receiver_ok = transfer_info["destination"] == expected_ata
    mint_ok = transfer_info["mint"] == IAT_MINT
    amount_ok = float(transfer_info["ui_amount"] or transfer_info["ui_amount_string"]) == float(order["price"])
    memo_ok = memo is not None and req.order_id in memo

    if sender_ok and receiver_ok and mint_ok and amount_ok and memo_ok:
        result = deliver_service(order, req.tx_signature)

        delivery_failed = isinstance(result, dict) and result.get("error") is not None

        if delivery_failed:
            update_agent_reputation_db(order.get("seller_id"), success=False)
            return {
                "status": "delivery_failed",
                "service": order["service"],
                "seller_id": order.get("seller_id"),
                "seller_source": order.get("seller_source"),
                "error": result
            }

        new_reputation = update_agent_reputation_db(order.get("seller_id"), success=True)

        save_processed_tx_db(req.tx_signature)
        update_order_delivered_db(req.order_id, req.tx_signature, result)

        return {
            "status": "paid",
            "service": order["service"],
            "seller_id": order.get("seller_id"),
            "seller_source": order.get("seller_source"),
            "new_reputation": new_reputation,
            "data": result
        }

    return {"status": "invalid_payment"}
